# Change these first
owner: devtdq1701 # Your GitHub organization or username, where this repository lives
repo: upptime-nextify # The name of this repository

sites:
  - name: Mobitopup
    url: https://napcard.voz.tech
    maxResponseTime: 3000
    method: GET
  - name: Test Telegram
    url: https://test.com
    maxResponseTime: 5000
    method: GET
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  theme: dark
  name: Upptime
  baseUrl: /upptime-nextify
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /upptime-nextify
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
